_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 41
                - 49
                - 53
                - 55
                - 80
            "2":
                - 1
                - 2
                - 3
                - 5
                - 41
                - 49
                - 53
                - 55
                - 80
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.7
            "8":
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
architecture:
    value: train_val_test_inception_v3
dataset:
    value: DeFungi-5
early stopping:
    value:
        min_delta: 0.0001
        patience: 30
epochs:
    value: 1000
factor:
    value: 0.05
learning_rate:
    value: 1e-05
optim:
    value: |-
        Adam (
        Parameter Group 0
            amsgrad: False
            betas: (0.9, 0.999)
            capturable: False
            differentiable: False
            eps: 1e-08
            foreach: None
            fused: None
            lr: 1e-05
            maximize: False
            weight_decay: 0
        )
scheduler_patience:
    value: 5
